name: Python Dashboard Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_LOCATION: your-python-dashboard-directory
  ELASTIC_BEANSTALK_NAME: Argentina-Dashboard
  ELASTIC_BEANSTALK_ENV_NAME: Argentina-Dashboard-env-1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r $PROJECT_LOCATION/requirements.txt

    - name: Run tests (if applicable)
      run: |
        python -m unittest discover $PROJECT_LOCATION/tests

    - name: Package application
      run: |
        cd $PROJECT_LOCATION
        zip -r ../dashboard.zip .

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.3.3
      with: 
        name: deploy-files
        path: dashboard.zip

  deploy:

    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/download-artifact@v4.1.7
      with:
        name: deploy-files
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Deploy to Elastic Beanstalk
      run: |
        aws elasticbeanstalk update-environment \
          --application-name ${{ env.ELASTIC_BEANSTALK_NAME }} \
          --environment-name ${{ env.ELASTIC_BEANSTALK_ENV_NAME }} \
          --version-label ${{ github.run_id }} \
          --source-bundle S3Bucket="${{ github.run_id }}.zip",S3Key="${{ github.run_id }}"
